# Generated by Django 2.2.1 on 2019-05-25 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=500)),
                ('img', models.ImageField(default='gallery/no-img.png', upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='MediaAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('surname', models.CharField(max_length=70)),
                ('img', models.ImageField(default='gallery/no-img.png', upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='MediaGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mgenre', models.CharField(choices=[('ACT', 'Action'), ('ADV', 'Adventure'), ('DRM', 'Drama'), ('CMDY', 'Comedy'), ('SYFY', 'SyFy')], default='ACT', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtype', models.CharField(choices=[('MV', 'Movie'), ('BK', 'Book'), ('SR', 'Series')], default='MV', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='gallery/no-img.png', upload_to='gallery')),
                ('authentication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(default=0)),
                ('review', models.CharField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Media')),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MediaAuthor'),
        ),
        migrations.AddField(
            model_name='media',
            name='mgenre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MediaGenre'),
        ),
        migrations.AddField(
            model_name='media',
            name='mtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MediaType'),
        ),
    ]
