# Generated by Django 2.2.1 on 2019-05-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='mgenre',
            field=models.CharField(choices=[('ACT', 'Action'), ('ADV', 'Adventure'), ('DRM', 'Drama'), ('CMDY', 'Comedy'), ('SYFY', 'SyFy')], default='ACT', max_length=2),
        ),
        migrations.AlterField(
            model_name='media',
            name='mtype',
            field=models.CharField(choices=[('MV', 'Movie'), ('BK', 'Book'), ('SR', 'Series')], default='MV', max_length=2),
        ),
        migrations.DeleteModel(
            name='MediaGenre',
        ),
        migrations.DeleteModel(
            name='MediaType',
        ),
    ]
