# Generated by Django 2.2.1 on 2019-05-26 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190525_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='date_added',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='media',
            name='date_published',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
