# Generated by Django 2.2.1 on 2019-05-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190526_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='mgenre',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('SyFy', 'SyFy')], default='Action', max_length=20),
        ),
        migrations.AlterField(
            model_name='media',
            name='mtype',
            field=models.CharField(choices=[('Movie', 'Movie'), ('Book', 'Book'), ('Series', 'Series')], default='Movie', max_length=2),
        ),
    ]
