# Generated by Django 2.2.1 on 2019-05-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190527_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='mtype',
            field=models.CharField(choices=[('Movie', 'Movie'), ('Book', 'Book'), ('Series', 'Series')], default='Movie', max_length=20),
        ),
    ]
