# Generated by Django 2.2.1 on 2019-05-27 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190527_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='date_added',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='media',
            name='date_published',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
