# Generated by Django 2.2.1 on 2019-05-27 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190527_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='date_added',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='media',
            name='date_published',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
